# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.1

pipelines:
  default:
    - step:
        script:
          # Print the Linux version.
          - uname -a
          # Print the gcc version.
          - gcc --version
          #  Install a CMake 3.0.2 version.
          - apt-get update -qq
          - apt-get install cmake -y
          # Print the CMake version.
          - cmake --version
          # Build debug project
          - ./Scripts/BuildDebugProject.sh
